config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  root 'home#index'

  get '/quienes_somos', to: 'home#quienes_somos'

  get '/solicitar_pqr', to: 'home#solicitar_pqr'

  get '/consultar_pqr', to: 'home#consultar_pqr'

  get '/iniciar_sesion', to: 'home#iniciar_sesion'
  
  get  '/new',  to: 'usuarios#new'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'

end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout "application", :except=> [:quienes_somos, :solicitar_pqr, :consultar_pqr, :iniciar_sesion]
  
  
  
  def index
    @titulo = "Empresa ABC -Inicio"
  end

  def quienes_somos
    @titulo = "Empresa ABC -Quienes Somos"
  end

  def solicitar_pqr
    @titulo = "Empresa ABC -Solicitar PQRS"
   # if Email.recepcion.deliver
    #  flash.now[:notice] = "Se ha enviado el correo"
    #else
     # flash.now[:notice] = "no se ha enviado correctamente"
    #end
  end

  def consultar_pqr
    @titulo = "Empresa ABC - Consultar PQRS"
  end

  def iniciar_sesion
    @titulo = "Empresa ABC - Iniciar Sesion"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end
  
  def create
     user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # Log the user in and redirect to the user's show page.
    else
      # Create an error message.
      flash[:danger] = 'Invalid email/password combination' # Not quite right!    
      render 'new'  
    end
  end
  
  def destroy
    
  end
  
  
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
    def mostrar_image(nombre, tamano)
       image_tag nombre, :size=>tamano 
    end
end

app/helpers/home_helper.rb
module HomeHelper
	def enlace(nombre,accion)
		link_to nombre, :action=>accion
	end


	def menu_navegacion(opciones)
		html = '<ul class="nav nav-pills">'
		opciones.each do |nombre,accion|
			html += '<li>' +  enlace(nombre, accion)   + '</li>'
		end
		html += '</ul>'

		return html.html_safe

	end

end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/home/consultar_pqr.html.erb
<h1><%= @titulo ||= "Empresa ABC" %></h1>
<p>Find me in app/views/home/consultar_pqr.html.erb</p>

app/views/home/index.html.erb
<% content_for :imagen do %>
<div class="row">
	<div class="span10 offset2"><%= image_tag "slide1.png", :size =>"800x100" %></div>
</div>
<% end %>

<h1><%= @titulo ||= "Curso Ruby on Rails" %></h1>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
proident, sunt in culpa qui officia deserunt mollit anim id est laborum.<p>

app/views/home/iniciar_sesion.html.erb
<% provide(:title, "Log in") %>
<h1>Log in</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:session, url: login_path) do |f| %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.submit "Log in", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>

app/views/home/quienes_somos.html.erb
<h1><%= @titulo ||= "Empresa ABC" %></h1>
<p>Find me in app/views/home/quienes_somos.html.erb</p>

app/views/home/solicitar_pqr.html.erb
<h2><%= @titulo ||= "Empresa ABC" %></h2>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:session, url: login_path) do |f| %>

      <%= f.label :nombre %>
      <%= f.text_field :nombre, class: 'form-control' %>
      
      <%= f.label :apellido %>
      <%= f.text_field :apellido, class: 'form-control' %>
      
      <%= f.label :tipo_de_identificacion  %>
      <%= f.text_field :tipo_de_identificacion, class: 'form-control' %>
      
       <%= f.label :cedula  %>
      <%= f.text_field :cedula, class: 'form-control' %>
      
      <%= f.label :telefono %>
      <%= f.text_field :telefono, class: 'form-control' %>
      
      <%= f.label :ciudad %>
      <%= f.text_field :ciudad, class: 'form-control' %>
      
      <%= f.label :direccion %>
      <%= f.text_field :direccion, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
      
      <%= f.label :Descripcion %>
      <%= f.text_area :message, :id => "message_area", :cols => 60, :rows => 5 %>
      
      
      
      <%= f.label :tipo_de_solicitud  %>
      <%= f.text_field :tipo_de_solicitud, class: 'form-control' %>
      
      <% f.label :archivo %><br>
      <%= f.file_field :archivo_adjunto %><br>
      
      

      <%= f.submit "Log in", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>
 </div>
    </div>

app/views/layouts/_cabecera.html.erb
<meta charset="UTF-8">
  <title><%= @titulo ||= "Empresa ABC" %></title>
  <link rel="icono" href="images/logo.png" type="image/x-icon"/>
  
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

app/views/layouts/_contenedor.html.erb
	<!-- Logo -->
		<%=link_to (image_tag "logo.png", :size=>"120x100", :alt=>"logo"),{:action=>"index"}, :id=>"logo" %>
		<!-- Final Logo -->

		<!-- Navegacion -->
		<nav>
    		<ul>

    			<li><%= link_to "Inicio", :action=>"index" %></li>
    			<li><%= link_to "¿Quiénes Somos?", :action=>"quienes_somos" %></li>
				<li><%= link_to "Iniciar Sesion", :action=>"iniciar_sesion" %></li>

    		</ul>
    	<!-- Final Navegacion -->
    	</nav>

app/views/layouts/_intro.html.erb
<div class="row hero-unit espacio">
      <div class="span4">
        <h3>Empresa ABC</h3>
      </div>
      
      <div class"span6">
          <%= mostrar_image "slide.jpg", "550x316" %>
          
      </div>
</div>
   
    

app/views/layouts/_servicios.html.erb
 <div class="row">
      <div class="span4">
        <h3>¿Quienes Somos?</h3>
          <p> Aqui va el texto de quienes somos</p>
            <%= link_to "Read more...", {:action=>"quienes_somos"}, :class=>"read_more" %>
      </div>
    
      <div class="span4">
        <h3>Solicitar PQRS</h3>
        <p> Aqui va el texto de contactenoss</p>
         <%= link_to "Solicitar", {:action=>"solicitar_pqr"}, :class=>"solicitar" %>
      </div>
      
      <div class="span4">
        <h3>Consultar PQRS</h3>
        <p> Aqui va el texto de contactenoss</p>
        <%= link_to "Consultar", {:action=>"consultar_pqr"}, :class=>"consultar" %>
      </div>
 </div>

<div class="holder_content1">
      <div class="group6">
        <%= yield %>
      </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE HTML>
<html lang="es">
<head>
	<meta charset="UTF-8">
	<title><%= @titulo ||= "Curso Rails - Santiago Ponce" %>  </title>
	<link rel="icon" href="images/favicon.gif" type="image/x-icon"/>
 <!--[if lt IE 9]>
 <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
  <script type="text/javascript" src=" https://ajax.googleapis.com/ajax/libs/jquery/1.6/jquery.js"></script>
	<%= stylesheet_link_tag    "application", :media => "all" %>
  	<%= javascript_include_tag "application" %>
  	<%= csrf_meta_tags %>
  
</head>
<body>
	<!--Contenedor-->
  <div id="container">

	<!--Cabecera-->
	<header>
		<!-- Logo -->
		<!-- Logo -->
		<%=link_to (image_tag "logo.png", :size=>"120x100", :alt=>"logo"), :action=> 'index', :id=>"logo" %>
		<!-- Final Logo -->

		<!-- Navegacion -->
		<nav>
    		<ul>

    			<li><%= link_to "Inicio",  :action=> 'index' %></li>
    			<li><%= link_to "¿Quiénes Somos?", quienes_somos_path %></li>
				<li><%= link_to "Iniciar Sesion", iniciar_sesion_path%></li>

    		</ul>
    	<!-- Final Navegacion -->
    	</nav>
		

		<!-- Final Cabecera-->
	</header>

	<!--Cabecera intro-->

   	<div id="intro">
   
   		<div class="group_bannner_right">
   			<%= image_tag "slide.jpg", :size=>"550x316", :alt=>"index" %>
   			
   		</div>
   
   		<header class="group_bannner_left">
   			<hgroup>
   				<h1>Empresa ABC</h1>
   				<h2>Santa marta - Magdalena</h2>
   			</hgroup>
   		</header>

   </div>
   <!--Final Cabecera intro-->

   <!--Servicios Destacados-->

   <div class="holder_content">
   
   <section class="group1">
   <h3>¿Quiénes Somos?</h3>
   	<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
   	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
   	quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
   	consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
   	cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
   	proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    <%= link_to "Read more...",quienes_somos_path, :class=>"read_more" %>

	</section>
	

     
   <section class="group2">
   <h3>Solicitar PQRS</h3>
   	<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
   	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
   	quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
   	consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
   	cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
   	proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
	<%= link_to "Read more...",solicitar_pqr_path, :class=>"read_more" %>

	</section>
       
   <section class="group3">
   <h3>Consultar PQRS</h3>
   	<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
   	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
   	quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
   	consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
   	cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
   	proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
	<%= link_to "Consultar",consultar_pqr_path, :class=>"read_more" %>

	</section>

  
   </div>
   <!--end holder-->


	<!-- Final contenedor -->
	</div>
</body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE HTML>
<html lang="es">
<head>
	<meta charset="UTF-8">
	<title><%= @titulo ||= "Curso Rails - Santiago Ponce" %>  </title>
	<link rel="icon" href="images/favicon.gif" type="image/x-icon"/>
 <!--[if lt IE 9]>
 <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
  <script type="text/javascript" src=" https://ajax.googleapis.com/ajax/libs/jquery/1.6/jquery.js"></script>
	<%= stylesheet_link_tag    "application", :media => "all" %>
  	<%= javascript_include_tag "application" %>
  	<%= csrf_meta_tags %>
  	<script language="javascript">
			$(document).ready(
				function (){
					$("#pikame").PikaChoose();
				});
		</script>
</head>
<body>
	<!--Contenedor-->
  <div id="container">

	<!--Cabecera-->
	<header>
		<!-- Logo -->
		<%=link_to (image_tag "logo.png", :size=>"120x100", :alt=>"logo"),{:action=>"index"}, :id=>"logo" %>
		<!-- Final Logo -->

		<!-- Navegacion -->
		<nav>
    		<ul>

    			<li><%= link_to "Inicio", :action=>"index" %></li>
    			<li><%= link_to "¿Quiénes Somos?", :action=>"quienes_somos" %></li>
				<li><%= link_to "Iniciar Sesion", :action=>"iniciar_sesion" %></li>

    		</ul>
    	<!-- Final Navegacion -->
    	</nav>

		<!-- Final Cabecera-->
	</header>


   <!-- Empieza contenido dinámico -->
	 <div id="formulario" class="row">
	 	<form>
	 		<%= yield %>
	 	</form>
	</div>
	<!-- Final contenedor -->
	</div>
<% if flash[:notice] %>
	<div class="row">
		<div class="span10 offset2 alert">
			<button type="button" class="close" data-dismiss="alert">&times;</button>
			<%= flash[:notice] %>
		</div>
	</div>
<% end %>
</body>
</html>

app/views/layouts/iniciar_sesion.html.erb
<!DOCTYPE HTML>
<html lang="es">
<head>
	<meta charset="UTF-8">
	<title><%= @titulo ||= "Curso Rails - Santiago Ponce" %>  </title>
	<link rel="icon" href="images/favicon.gif" type="image/x-icon"/>
 <!--[if lt IE 9]>
 <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
  <script type="text/javascript" src=" https://ajax.googleapis.com/ajax/libs/jquery/1.6/jquery.js"></script>
	<%= stylesheet_link_tag    "application", :media => "all" %>
  	<%= javascript_include_tag "application" %>
  	<%= csrf_meta_tags %>
  	<script language="javascript">
			$(document).ready(
				function (){
					$("#pikame").PikaChoose();
				});
		</script>
</head>
<body>
	<!--Contenedor-->
  <div id="container">

	<!--Cabecera-->
	<header>
		<!-- Logo -->
		<%=link_to (image_tag "logo.png", :size=>"120x100", :alt=>"logo"),{:action=>"index"}, :id=>"logo" %>
		<!-- Final Logo -->

		<!-- Navegacion -->
		<nav>
    		<ul>

    			<li><%= link_to "Inicio", :action=>"index" %></li>
    			<li><%= link_to "¿Quiénes Somos?", :action=>"quienes_somos" %></li>
				<li><%= link_to "Iniciar Sesion", :action=>"iniciar_sesion" %></li>

    		</ul>
    	<!-- Final Navegacion -->
    	</nav>

		<!-- Final Cabecera-->
	</header>


   <!-- Empieza contenido dinámico -->
	 <div id="formulario" class="row">
	 	<form>
	 		<%= yield %>
	 	</form>
	</div>
	<!-- Final contenedor -->
	</div>
<% if flash[:notice] %>
	<div class="row">
		<div class="span10 offset2 alert">
			<button type="button" class="close" data-dismiss="alert">&times;</button>
			<%= flash[:notice] %>
		</div>
	</div>
<% end %>
</body>
</html>

app/views/usuarios/new.html.erb
<h1>Usuarios#new</h1>
<p>Find me in app/views/usuarios/new.html.erb</p>